### ISSUE TITLE
Expose an API for interacting directly with a module's memory

### ISSUE THREAD

**Issue by alexdovzhanyn** [ElixiumNetwork/WaspVM#25]
It should work similarly to how the browser allows Javascript code to access wasm memory. This will allow more dynamic applications to be built on top of the virtual machine (such as things that interact with a database).

**Comment by OvermindDL1** [comment]
Plus flat out serialization in or out of the system.  ^.^

**Comment by alexdovzhanyn** [comment]
Added in #27
